pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - label!=early-semver-major
      - label!=semver-spec-major
      - "#files=1"
      - "#approved-reviews-by>=1"    
      - check-success=CI - Jenkins
      - author=scala-steward-baeldung[bot]
      - or:
        - label=early-semver-minor
        - label=early-semver-patch
    actions:
      merge:
        method: merge
      delete_head_branch:
